config/routes.rb
Rails.application.routes.draw do
  root 'users#log_in'
  get '/registration', to: 'users#registration'
  post '/sign_in', to: 'users#sign_in'
  get 'user_success', to: 'users#sucess'
  delete '/log_out', to: 'users#log_out'
  resources :users
  resources :users do
    resources :tasks
  end
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks
    has_secure_password
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :user_present
  def current_user
    authenticate_user ? User.find(session[:user_id])  : nil
  end
  private 
  def authenticate_user
    session[:user_id].present?
  end
  def user_present
    unless current_user.present?
      redirect_to root_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @task = User.find(params[:user_id]).tasks
    end
    def new  
        @task = Task.new
    end
    def create
        s = session[:user_id]
        @tasks = User.find(s).tasks.create(title: params[:task][:title])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :user_present ,only: [:sign_in , :log_in, :registration, :create,:sucess, :show]
  before_action :user_active ,only: [:show]
  def log_in
    @author = User.new
  end
  def registration
    @author = User.new
  end
  def sign_in
    @user = User.find_by(email: user_params['email'])
    if @user && @user.authenticate(user_params[:password])
        session[:user_id] = @user.id
        redirect_to(@user)
    else
      redirect_to root_path
    end
  end
  def sucess 
  end
  def log_out
    session[:user_id] = nil
    redirect_to root_path
  end
  def show
    if current_user.present?
      @user = User.find(session[:user_id])
    else
      @user = User.find(params[:id])
    end
      @book = @user.tasks
  end
  def index 
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/user_success'
    else
      puts 'wrong'
    end
  end
  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
    def user_active
      if current_user.present?
        @user = User.find(session[:user_id])
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskMgmt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h3> task created sucessfully <h3>

app/views/tasks/index.html.erb
<% @task.each do |s| %>
  <%=  s.title %>
  <%=  s.description %>
<% end %>

app/views/tasks/new.html.erb
<%= form_with(model: @task, url: tasks_path, method: :post) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
  
    <%= form.label :description %>
    <%= form.text_field :description %>
    <%= form.submit %>
  <% end %>
  

app/views/users/log_in.html.erb
<%= form_with(model: @author, method: :post, url: '/sign_in', local: true) do |form| %>
  <%= javascript_include_tag 'rk' %>
  
      <div style="background: linear-gradient(135deg, rgba(114,182,229,1) 0%, rgba(143,116,195,1) 98%); height: 100vh;">
          <div style = "height: 70vh; width: 95vh; " class="col-md-6 offset-md-3 center-div ">
              <div class = "container h-100 " style = "background: white; " >
                  <div class = "row align-items-center h-100 p-3" >
                        <div class= "col" >
                          <h3 class="text-secondary">Log in </h3>
                          <div class= "row">
                              <div class= "col" style = "outline: none;">
                                  <%= form.label :email, "Email", class: 'medium' %>
                                  <%= form.email_field :email, placeholder: 'Enter your email' ,class: 'rk form-control  mt-1 mb-2 p-2' %>
                              </div>
                          </div>
                            <div class= "row">
                                <div class= "col">
                                  <%= form.label :password, "Password", class: 'medium' %>
                                  <%= form.password_field :password, placeholder: 'Enter your password', class: ' rk form-control mt-1 p-2' %>
                                </div>
                            </div>
                          
                            <div >
                                <%= form.submit "Submit", class: 'custom-btn form-control form-control-sm' %>
                            </div>
                          <div class ="row">
                                <%= link_to 'new registration', "/registration" %>
                          </div>
                        </div>
                      
                  </div>
              </div>
          </div>
      </div>    
  <% end %>
  

app/views/users/registration.html.erb
<%= form_with model: @author, url: '/users'  do |form| %>
    <%= javascript_include_tag 'rk' %>
    
        <div style="background: linear-gradient(135deg, rgba(114,182,229,1) 0%, rgba(143,116,195,1) 98%); height: 100vh;">
            <div style = "height: 70vh; width: 95vh; " class="col-md-6 offset-md-3 center-div ">
                <div class = "container h-100 " style = "background: white; " >
                    <div class = "row align-items-center h-100 p-3" >
                        <div class= "col" >
                            <h3 class="text-secondary">Registration</h3>
                            <div class = "row">
                                <div class = "col">
                                    <%= form.label :name, "Name", class: 'medium' %>
                                    <%= form.text_field :name , placeholder: 'Enter your name', class: ' rk form-control  mt-1 mb-2 p-2'%>
                                </div>
                                <div class = 'col'>
                                    <%= form.label :username, "Username" , class: 'medium' %>
                                    <%= form.text_field :username, placeholder: 'Enter your username', class: ' rk form-control  mt-1 p-2 mb-2 mr-5' %>
                                </div>
                            </div>
                            <div class= "row">
                                <div class= "col" style = "outline: none;">
                                    <%= form.label :email, "Email", class: 'medium' %>
                                    <%= form.email_field :email, placeholder: 'Enter your email' ,class: 'rk form-control  mt-1 mb-2 p-2' %>
                                </div>
                                <div class = "col">
                                    <%= form.label :phone_number, "Phone Number", class: 'medium' %>
                                    <%= form.text_field :phone_number , placeholder: 'Enter your number',class: ' rk form-control mt-1 p-2 mb-2' %>
                                </div>
                            </div>
                            <div class= "row">
                                <div class= "col">
                                    <%= form.label :password, "Password", class: 'medium' %>
                                    <%= form.password_field :password, placeholder: 'Enter your password', class: ' rk form-control mt-1 p-2' %>
                                </div>
                                <div class = "col">
                                    <%= form.label :confirm_password, "Confirm Password", class: 'medium' %>
                                    <%= form.text_field :confirm_password, placeholder: 'Confirm your password', class: 'rk form-control  mt-1 p-2' %>
                                    <br>
                                </div>
                            </div>
                            
                            <div class='row'>
                                <div class= 'col'>
                                    <%= form.label :gender, 'Gender', class: 'medium' %>
                                </div>
                            </div>  <br>
                            <div class = 'row'  > 
                                <div class = 'col' >
                                    <%= form.radio_button :gender, "male" %>
                                    <%= form.label :gender_male, "Male", class: 'text-secondary' %>
                                </div>
                                <div class= 'col'>    
                                    <%= form.radio_button :gender, "female" %>
                                    <%= form.label :gender_female, "Female", class: 'text-secondary' %>
                                </div>
                                <div class= 'col'>    
                                    <%= form.radio_button :gender, "not_say" %>
                                    <%= form.label :gender_not_say, "Prefer not to say", class: 'text-secondary' %>
                                </div>
                            </div> <br>
                            <div >
                                <%= form.submit "Register", class: 'custom-btn form-control form-control-sm' %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    <% end %>

app/views/users/show.html.erb
<h1>User Information</h1>

<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>
<%= link_to "Sign out", "/log_out", method: :delete %> <br>
<%= link_to ' create task', new_user_task_path(user_id: @user.id), method: :get %> <br>
<%= link_to 'view tasks', user_tasks_path(user_id: @user.id), method: :get %>

app/views/users/sucess.html.erb
<h2> Registration sucessful </h1>
<h3> please log in with your email id and password </h3>
<%= link_to 'click here', root_path %>